server:
  port: ${SERVER_PORT:8088}

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/grocery_store
#    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop

    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect


logging:
  config: classpath:logback.xml

# application used properties
application:
  security:
    jwt:
      secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    session:
      expiration-in-hours: 24
    while-list-urls: /api/v1/auth/**;/api/v1/hello;/api/v1/users/**;



